services:
  wildstar:
    image: mariadb:11.6
    restart: always
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'DisIssssR00t'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '127.0.0.1:3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - wildstar-db:/var/lib/mysql
volumes:
  wildstar-db:
